[package]
name = "square"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.1"
solana-program = "2.0.10"

[dev-dependencies]
solana-program-test = "2.0.10"
solana-sdk = "2.0.1"

[lib]
crate-type = ["cdylib", "lib"]